name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017

    steps:
      - name: 1. Checkout source code
        uses: actions/checkout@v4

      - name: 2. install pnpm
        uses: pnpm/action-setup@v4

      - name: 3. install node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 4. install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: 5. build Monorepo contracts
        run: pnpm --filter @repo/contracts build

      - name: 6. check Type-check & Lint
        run: |
          pnpm exec tsc --noEmit
          pnpm lint

      - name: 7. run 100% test
        run: pnpm test
        env:
          NODE_ENV: test
          PORT: 3000
          MONGO_URI: mongodb://127.0.0.1:27017/test_db
          JWT_KEY: test_super_secret_jwt_key_123456_for_ci
